### ISSUE TITLE
Support for Cocoapods

### ISSUE THREAD

**Issue by Querschlag** [emaloney/CleanroomLogger#62] opened 2016-11-09 14:59 UTC
I really like the approach of this logger library, but we use CocoaPods in our apps.
Are there any plans to add this project to the CocoaPods repo?

**Comment by DominikPalo** [comment] 2016-12-27 15:42
https://github.com/emaloney/CleanroomLogger/issues/10#issuecomment-165212635

**Comment by emaloney** [comment] 2016-12-31 17:52
Closing as duplicate of #10.

**Closed by emaloney** 2016-12-31 17:52 UTC

**Comment by emaloney** [comment] 2017-03-07 22:49
As [discussed in another thread](https://github.com/emaloney/CleanroomLogger/issues/69#issuecomment-284852205), I can now state definitively that we will never be adding Cocoapods support to CleanroomLogger.
